spring:
  cloud:
    config:
      server:
        git:
          uri: 'file://${user.home}/Documents/Lessons/Portfolio/config-repo'
          searchPaths: '{application}'
          clone-on-start: true
server:
  port: 8888