spring:
  profiles:
    include: 'kafka'
  application:
    name: 'ms-coordinates'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics